[workspace]
members = [
    "datanymizer_engine",
    "dumpers/datanymizer_dumper",
    "dumpers/mssql_datanymizer_dumper",
    "dumpers/pg_datanymizer_dumper",
    "cli/mssql_datanymizer",
    "cli/pg_datanymizer",
]
