version: '3.2'
services:
  pg_datanymizer:
    build:
      context: ..
      dockerfile: demo/Dockerfile.pg_datanymizer
    image: pg_datanymizer
    volumes:
      - ./dvdrental.yml:/dvdrental.yml

  pg_database:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
    depends_on:
      - pg_datanymizer
    ports:
      - "5432:5432"
    volumes:
      - demo-volume:/demo/:rw

volumes:
  demo-volume:
