name: Audit
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install Cargo audit
        run: cargo install cargo-audit
      - name: Run audit
        run: cargo audit
