# Github workflow files do not support YAML anchors.
name: CI
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo mkdir /usr/include/x86_64-linux-musl
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/asm && \
              ln -s /usr/include/asm-generic /usr/include/x86_64-linux-musl/asm-generic && \
              ln -s /usr/include/linux /usr/include/x86_64-linux-musl/linux && \
              mkdir /musl && \
              wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1l.tar.gz && \
              tar zxvf OpenSSL_1_1_1l.tar.gz && \
              cd openssl-OpenSSL_1_1_1l/ && \
              CC="musl-gcc -fPIE -pie" ./Configure no-shared no-async --prefix=/musl --openssldir=/musl/ssl linux-x86_64 && \
              make depend && \
              make -j$(nproc) && \
              make install
          export PKG_CONFIG_ALLOW_CROSS=1
          export OPENSSL_STATIC=true
          export OPENSSL_DIR=/musl
          cargo build --release --target x86_64-unknown-linux-musl
